spring:
  application:
    name: app-state-management-backend
  datasource:
    url: jdbc:mysql://localhost:3306/db-app-state-management
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true

